const $=s=>document.querySelector(s);
function render(){
 $('#metrics').innerHTML=GPM.metrics.map(x=>`<div class="metric"><span class="label">${x[0]}</span><span class="badge ${x[4]}">${x[3]}</span><div class="value">${x[1]}</div><div class="delta ${x[2].includes('↘')?'down':'up'}">${x[2]}</div><div class="bar ${x[4]}"><i></i></div></div>`).join('');
 $('#brief').innerHTML=GPM.brief.map(x=>`<article class="panel brief-card"><div class="risk-head"><span class="tag ${x.type}">${x.tag}</span><span class="score ${x.type==='red'?'trusted':''}">${x.trust}</span></div><h2>${x.title}</h2><p>${x.text}</p><div class="impact ${x.type==='red'?'risk-impact':''}">${x.impact}</div><div class="eyebrow" style="margin-top:10px">◷ ${x.time}</div></article>`).join('');
 $('#ops').innerHTML=GPM.ops.map(x=>`<div class="op"><span class="label eyebrow">${x[0]}</span><span class="badge ${x[4]}" style="float:right">${x[3]}</span><div class="value">${x[1]}</div><div class="delta ${x[2].includes('↘')?'down':'up'}">${x[2]}</div></div>`).join('');
 $('#inventory').innerHTML=GPM.inventory.map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td><td>${x[2]}</td><td>${x[3]}</td><td><span class="status ${x[5]}">${x[4]}</span></td></tr>`).join('');
 $('#heatmap').innerHTML='<div class="head"></div>'+GPM.channels.map(c=>`<div class="head">${c}</div>`).join('')+GPM.matrix.map(r=>`<div class="name">${r[0]}</div>`+r[1].map(v=>`<div class="${v<30?'h-red':v<36?'h-yellow':v<42?'h-green':'h-cyan'}">${v}</div>`).join('')).join('');
 $('#risks').innerHTML=GPM.risks.map(r=>`<article class="risk"><div class="risk-head"><span class="severity ${r.cls}">${r.sev}</span><span class="score ${r.cls==='medium'?'caution':'trusted'}">${r.trust}</span></div><h4>${r.title}</h4><p>${r.text}</p><div class="impact ${r.sev==='CRITICAL'?'risk-impact':''}">${r.impact}</div></article>`).join('');
 $('#actions').innerHTML=GPM.actions.map(a=>`<article class="action"><div class="risk-head"><span class="tag cyan">${a.cls}</span><span class="score trusted">${a.trust}</span></div><h4>${a.title}</h4><p>${a.text}</p><div class="impact">${a.impact}</div></article>`).join('');
}
$('#askBtn').addEventListener('click',()=>{const q=$('#question').value.toLowerCase();let answer=q.includes('mouthwash')?'<strong>Verified answer:</strong> Mouthwash is high risk because demand is +38% WoW in the dental channel, on-hand cover is only 6 days, and supplier lead time is 18 days. The largest buyer also has a 32% overdue-AR concentration. <br><br><span class="up">Trust: 93/100 · Evidence: inventory snapshot + sales demand + receivables.</span>':'<strong>Verified answer:</strong> I can answer this from the current enterprise snapshot. Try asking about revenue, margin, inventory, receivables, risks or recommended actions. <br><br><span class="up">Trust: 90/100.</span>';$('#answer').innerHTML=answer;$('#answer').classList.remove('hidden')});
render();
